<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Опубликовано',
    'Author:' => 'Автор:',
    'Content' => 'Содержимое',
    'Create' => 'Опубликовать',
    'Create post' => 'Создать пост',
    'Created At' => '',
    'Date publication:' => 'Дата публикации:',
    'Deleted' => 'Удаленно',
    'Edit post' => 'Изменить',
    'ID' => '',
    'Inactive' => 'Проверяется модератором',
    'Posts' => 'Посты',
    'Publish post' => 'Опубликовать пост',
    'Slug' => '',
    'Status' => 'Статус',
    'The requested article does not exist.' => '',
    'The requested user does not exist.' => 'Запрошенная страница не найдена.',
    'Title' => 'Название поста',
    'Update post' => 'Редактировать пост',
    'Updated At' => '',
    'User ID' => '',
    'You are not allowed to perform this action.' => 'Вам не разрешено выполнять это действие.',
    'Your post was successfully added. Therefore your post will be published as it will be verified by the Administrator.' => 'Ваш пос был успешно добавлен. Ваш пост будет опубликован только после проверки администратором сайта.',
    'Your post was successfully updated.' => 'Ваше сообщение было успешно обновлено.',
    'read more...' => 'читать далее...',
];
