<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Author:' => 'Автор:',
    'Create' => 'Опубликовать',
    'Create post' => 'Создать пост',
    'Delete' => 'Удалить',
    'Date publication:' => 'Дата публикации:',
    'Edit post' => 'Изменить',
    'News' => 'Новости',
    'Publish post' => 'Опубликовать пост',
    'The requested article does not exist.' => '',
    'The requested user does not exist.' => 'Пользователь не найден.',
    'Update post' => 'Редактировать пост',
    'You are not allowed to perform this action.' => 'Вам не разрешено выполнять это действие.',
    'Your post was successfully added. Therefore your post will be published as it will be verified by the Administrator.' => 'Ваш пос был успешно добавлен. Ваш пост будет опубликован только после проверки администратором сайта.',
    'Your post was successfully updated.' => 'Ваше сообщение было успешно обновлено.',
    'Your post was successfully deleted.' => 'Ваше сообщение было успешно удалено.',
    'Failed to delete project.' => 'Ошибка при удалении сообщения.',
    'read more...' => 'читать далее...',
];
