<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activated' => 'Активирован',
    'Auth Key' => 'Ключ аутентификации',
    'Blocked' => 'Заблокирован',
    'Cancel' => 'Отмена',
    'Change password' => 'Изменение пароля',
    'Change picture' => 'Изменить фото',
    'Change the password' => 'Изменить пароль',
    'Created At' => 'Создан',
    'Current password' => 'Текущий пароль',
    'Deleted' => 'Удалён',
    'Edit profile' => 'Редактировать профиль',
    'Email' => 'Почта',
    'Email Verified' => 'Почта подтверждена',
    'Email verification token' => 'Токен подтверждения почты',
    'Facebook' => 'Facebook',
    'Full name' => 'Полное имя',
    'Github' => 'GitHub',
    'ID' => 'ID',
    'Inactivated' => 'Деактивирован',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
    'New password' => 'Новый пароль',
    'No Facebook' => 'Нет аккаунта Facebook',
    'No Github' => 'Нет аккаунта Github',
    'No Twitter' => 'Нет аккаунта Twitter',
    'No Website' => 'Нет сайта',
    'Password' => 'Пароль',
    'Password Hash' => 'Хеш пароля',
    'Password Reset Token' => 'Токен восстановления пароля',
    'Password reset token cannot be blank.' => 'Токен восстановления пароля не может быть пустым',
    'Posts from {username}' => 'Посты от {username}',
    'Remember me' => 'Запомнить',
    'Repeat password' => 'Повторите пароль',
    'Resend At' => 'Повторно отослан',
    'Resend letters will be possible {time}.' => 'Повторно отправить письмо с подтверждением, возможно будет с {time}.',
    'Send' => 'Отправить',
    'Site' => 'Сайт',

    'Status' => 'Статус',

    'The email address is confirmed.' => 'Ваша почта подтверждена.',
    'The email address is not confirmed, {resend}' => 'Адрес почты не подтверждён, {resend}',
    'The email address is not confirmed.' => 'Адрес почты не подтверждён.',
    'The password was successfully changed.' => 'Пароль был успешно изменён.',
    'The profile was successfully changed.' => 'Профиль был успешно изменён.',
    'There is no user with such email.' => 'Нет пользователя с такой почтой.',
    'This email address has already been taken.' => 'Почта уже занята.',
    'This username has already been taken.' => 'Имя пользователя уже занято.',
    'Twitter' => 'Twitter',
    'Update' => 'Изменить',
    'Updated At' => 'Обновлён',
    'Username' => 'Имя пользователя',
    'Wrong password reset token.' => 'Неправильный токен восстановления пароля.',
    'resend the confirmation.' => 'повторно отправить подтверждение?',
];
