<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Project' => 'Добавить проект',
    'Add Question' => 'Добавить вопрос',
    'Add screenshots' => 'Добавить скриншоты',
    'Allow to upload JPEG/PNG files.' => 'Можно загружать JPEG и PNG.',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите выполнить удаление?',
    'Basic information' => 'Общая информация',
    'Body' => 'Текст',
    'Change' => 'Сменить',
    'Change password' => 'Сменить пароль',
    'Change picture' => 'Сменить изображение',
    'Chat' => 'Чат',
    'Create Question' => 'Создать вопрос',
    'Create post' => 'Создать пост',
    'Created At' => 'Создан',
    'Current Password' => 'Текущий пароль',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit profile' => 'Редактировать профиль',
    'Email' => 'Email',
    'Extensions' => 'Расширения',
    'Forum' => 'Форум',
    'Get last stable version:' => 'Последняя стабильная версия:',
    'Guide' => 'Руководство',
    'ID' => 'ID',
    'Image files' => 'Файлы изображений',
    'Leave feedback' => 'Оставить пожелание',
    'Link' => 'Ссылка',
    'Linked {client} account.' => '{client} подключен.',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Member List' => 'Сообщество',
    'My profile' => 'Мой профиль',
    'Name' => 'Имя',
    'Navigation' => 'Навигация',
    'Not verified' => 'Не подтверждён',
    'Password' => 'Пароль',
    'Post Your Answer' => 'Опубликовать ответ',
    'Posts' => 'Посты',
    'Project ID' => 'ID проекта',
    'Projects' => 'Проекты',
    'Projects based on Yii framework' => 'Проекты на Yii',
    'Public chat' => 'Открытый чат',
    'Publish' => 'Опубликовать',
    'Publish post' => 'Опубликовать пост',
    'Question ID' => 'ID вопроса',
    'Questions' => 'Вопросы',
    'Registration' => 'Регистрация',
    'Repeat Password' => 'Повторите пароль',
    'Report a bug' => 'Сообщить об ошибке',
    'Save' => 'Сохранить',
    'Signup' => 'Зарегистрироваться',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Support' => 'Поддержка',
    'The current password is incorrect.' => 'Текущий пароль не верен.',
    'Title' => 'Заголовок',
    'To web' => 'На сайт',
    'Twitter' => 'Twitter',
    'Unable to link {client} account. There is another user using it.' => 'Не удалось подключить {client}. Он уже используется другим пользователем.',
    'Unable to link {client} account: {errors}' => 'Не удалось подключить {client}: {errors}',
    'Update' => 'Обновить',
    'Update post' => 'Обновить пост',
    'Update question' => 'Обновить вопрос',
    'Updated At' => 'Обновлён',
    'User ID' => 'ID пользователя',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login first and then link it from your settings.' => 'Пользователь с таким же email как в {client} уже существует, но не привязан. Войдите и попробуйте привязать его в настройках.',
    'Username' => 'Имя пользователя',
    'Verified' => 'Проверен',
    'View Profile' => 'Профиль',
    'View Profile - {username}' => 'Профиль {username}',
    'Yii community' => 'Сообщество Yii',
    'Yii is a high-performance PHP framework best for developing Web 2.0 applications.' => 'Yii — это высокопроизводительный PHP фреймворк, отлично подходящий для Web 2.0 приложений.',
    'Your Answer' => 'Ваш ответ',
    'Your answer published' => 'Ваш ответ опубликован',
    'no site' => 'нет сайта',
    '{n, plural, =0{No answers} =1{One answer} other{# answers}}' => '{n, plural, =0{Нет ответов} =1{Один ответ} one{# ответ} few{# ответов} many{# ответов} other{# ответа}}',
    '{n, plural, =0{answers} =1{answer} other{answers}}' => '{n, plural, =0{ответов} =1{ответ} one{ответ} few{ответов} many{ответов} other{ответа}}',
];
