<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Project' => 'Добавить проект',
    'Add screenshots' => 'Добавить скриншоты',
    'Allow to upload JPEG/PNG files.' => 'Можно загружать JPEG и PNG.',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите выполнить удаление?',
    'Body' => 'Текст',
    'Chat' => 'Чат',
    'Color' => 'Цвет',
    'Create' => 'Создать',
    'Create Tag' => 'Создать тег',
    'Created At' => 'Создан',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit profile' => 'Редактировать профиль',
    'Extensions' => 'Расширения',
    'Forum' => 'Форум',
    'Guide' => 'Руководство',
    'ID' => 'ID',
    'If you forgot your password you can <a href="{link}">reset it</a>.' => 'Если забыли пароль, то можете <a href="{link}">его сбросить</a>.',
    'Image files' => 'Файлы изображений',
    'It\'s not the correct current password.' => 'Введённый текущий пароль не совпадает.',
    'Link' => 'Ссылка',
    'Linked {client} account.' => '{client} подключен.',
    'Login' => 'Войти',
    'Name' => 'Имя',
    'Parent ID' => '',
    'Position' => 'Позиция',
    'Project ID' => 'ID проекта',
    'Projects' => 'Проекты',
    'Projects based on Yii framework' => 'Проекты на Yii',
    'Question ID' => 'ID вопроса',
    'Registration' => 'Регистрация',
    'Reset password' => 'Восстановление пароля',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Select parent' => '',
    'Signup' => 'Зарегистрироваться',
    'Social network {client} has been successfully disabled.' => 'Социальная сеть {client} была успешно отключена.',
    'Status' => 'Статус',
    'Tag ID' => '',
    'Tags' => 'Теги',
    'The requested page does not exist.' => 'Запрошенная страница не найдена.',
    'Title' => 'Заголовок',
    'To web' => 'На сайт',
    'Unable to link {client} account. There is another user using it.' => 'Не удалось подключить {client}. Он уже используется другим пользователем.',
    'Unable to link {client} account: {errors}' => 'Не удалось подключить {client}: {errors}',
    'Unable to save user: {errors}' => 'Не удалось сохранить пользователя: {errors}',
    'Unable to save {client} account: {errors}' => 'Не удалось сохранить {client}: {errors}',
    'Update' => 'Обновить',
    'Update post' => 'Обновить пост',
    'Update {modelClass}: ' => 'Обновить {modelClass}',
    'Updated At' => 'Обновлён',
    'User ID' => 'ID пользователя',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Пользователь с такой же почтой как в {client} уже существует. Войдите чтобы привязать его.',
    'Users' => 'Пользователи',
    'Yii community' => 'Сообщество Yii',
    'Yii is a high-performance PHP framework best for developing Web 2.0 applications.' => 'Yii — это высокопроизводительный PHP фреймворк, отлично подходящий для Web 2.0 приложений.',
    'Your answer published' => 'Ваш ответ опубликован',
    'Your answer was updated' => 'Ваш ответ обновлён',
    'or {n} version' => 'или {n} версию',
];
