<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '---' => '',
    'Add Question' => 'Добавить вопрос',
    'All questions' => 'Все вопросы',
    'Answer Count' => '',
    'Body' => '',
    'Created At' => '',
    'Favorite Count' => '',
    'Favorites' => 'Избранные вопросы',
    'Frequency' => '',
    'ID' => '',
    'My questions' => 'Мои вопросы',
    'Name' => '',
    'Question ID' => '',
    'Questions' => 'Вопросы',
    'Questions are missing.' => 'Вопросы отсутствуют.',
    'Resolve' => 'Вопрос решен!',
    'Solution' => '',
    'Solved questions' => 'Решенные вопросы',
    'Sort by' => 'Сортировать по',
    'Status' => '',
    'Tag ID' => '',
    'Tags' => 'Теги',
    'Tags are missing' => '',
    'Title' => '',
    'Unanswered' => 'Без ответа',
    'Updated At' => '',
    'User ID' => '',
    'View Count' => '',
    '{n, plural, =0{answers} =1{answer} other{answers}}' => '{n, plural, =0{ответов} =1{ответ} one{ответ} few{ответов} many{ответов} other{ответа}}',
];
