<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A reminder letter with instructions was sent.' => '',
    'Activated' => '',
    'Active' => 'Активный',
    'Auth Key' => '',
    'Blocked' => '',
    'Change password' => 'Изменить пароль',
    'Change picture' => 'Изменить фото',
    'Created At' => '',
    'Current password' => 'Текущий пароль',
    'Delete' => 'Удалённый',
    'Deleted' => '',
    'Edit profile' => 'Редактировать профиль',
    'Email' => '',
    'Email Verified' => '',
    'First name' => 'Имя',
    'Github' => '',
    'ID' => '',
    'Inactivated' => '',
    'Last name' => 'Фамилия',
    'New password' => 'Новый пароль',
    'No Github' => 'Нет аккаунта Github',
    'No Website' => 'Нет сайта',
    'Password' => 'Пароль',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Password reset token cannot be blank.' => '',
    'Remember me' => 'Запомнить',
    'Repeat password' => 'Повторите пароль',
    'Resend At' => '',
    'Resend letters will be possible {time}.' => '',
    'Send' => 'Отправить',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Thank you, Your e-mail address was successfully confirmed.' => '',
    'The email address is confirmed.' => '',
    'The email address is not confirmed, {resend}' => '',
    'The email address is not confirmed.' => '',
    'The password was successfully changed.' => '',
    'The profile was successfully changed.' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Updated At' => '',
    'Username' => 'Имя',
    'Verified Token' => '',
    'Wrong confirmed token.' => '',
    'Wrong password reset token.' => '',
    'resend the confirmation.' => '',
];
